version: '2'

services:
  nlp:
    build: .
    volumes:
      - ./app:/app
      - ./embeddings:/root/.flair/embeddings
      - ./models:/root/.flair/models
    ports:
      - 8001:8001
    environment:
      USE_EMBEDDINGS: 'False'
      USE_NER: 'True'
    entrypoint: /bin/bash -c "waitress-serve --listen 0.0.0.0:8001 app:__hug_wsgi__"
    stdin_open: true
    tty: true